name: Build and test

on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0
      - run: |
          pwd
          ls -la



